/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[4],{648:function(ya,ua,h){h.r(ua);var ma=h(0),na=h(670),oa=h(671),ja;(function(ia){ia[ia.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";ia[ia.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";ia[ia.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ja||(ja={}));ya=function(){function ia(fa){this.ba=fa;this.state=ja.EXTERNAL_XFDF_NOT_REQUESTED}ia.prototype.eGa=function(){var fa=this;return function(z,
y,n){return Object(ma.b)(fa,void 0,void 0,function(){var e,a,f,r,b,w,ba,ca=this,ha;return Object(ma.d)(this,function(x){switch(x.label){case 0:if(this.state!==ja.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.ba.getDocument().Qz();return[4,this.pDa(e)];case 1:a=x.aa(),f=this.Bwa(a),this.sV=null!==(ha=null===f||void 0===f?void 0:f.parse())&&void 0!==ha?ha:null,this.state=null===this.sV?ja.EXTERNAL_XFDF_NOT_AVAILABLE:ja.EXTERNAL_XFDF_AVAILABLE,x.label=2;case 2:if(this.state===ja.EXTERNAL_XFDF_NOT_AVAILABLE)return n(z),
[2];r=new DOMParser;b=r.parseFromString(z,"text/xml");y.forEach(function(aa){ca.merge(b,ca.sV,aa-1)});w=new XMLSerializer;ba=w.serializeToString(b);n(ba);return[2]}})})}};ia.prototype.F0=function(fa){this.pDa=fa};ia.prototype.Vf=function(){this.sV=void 0;this.state=ja.EXTERNAL_XFDF_NOT_REQUESTED};ia.prototype.Bwa=function(fa){return fa?Array.isArray(fa)?new na.a(fa):"string"!==typeof fa?null:(new DOMParser).parseFromString(fa,"text/xml").querySelector("xfdf > add")?new na.a(fa):new oa.a(fa):null};
ia.prototype.merge=function(fa,z,y){var n=this;0===y&&(this.MKa(fa,z.pv),this.PKa(fa,z.XU));var e=z.ea[y];e&&(this.QKa(fa,e.fv),this.SKa(fa,e.Uka,z.Xs),this.RKa(fa,e.page,y),this.OKa(fa,e.l9));e=this.ba.Cb();if(y===e-1){var a=z.Xs;Object.keys(a).forEach(function(f){a[f].sX||n.Uda(fa,f,a[f])})}};ia.prototype.MKa=function(fa,z){null!==z&&(fa=this.jD(fa),this.ix(fa,"calculation-order",z))};ia.prototype.PKa=function(fa,z){null!==z&&(fa=this.jD(fa),this.ix(fa,"document-actions",z))};ia.prototype.QKa=function(fa,
z){var y=this,n=this.iD(fa.querySelector("xfdf"),"annots");Object.keys(z).forEach(function(e){y.ix(n,'[name="'.concat(e,'"]'),z[e])})};ia.prototype.SKa=function(fa,z,y){var n=this;if(0!==z.length){var e=this.jD(fa);z.forEach(function(a){var f=a.getAttribute("field"),r=y[f];r&&(n.Uda(fa,f,r),n.ix(e,"null",a))})}};ia.prototype.Uda=function(fa,z,y){var n=this.jD(fa),e=n.querySelector('ffield[name="'.concat(z,'"]'));null!==y.QL&&null===e&&this.ix(n,'ffield[name="'.concat(z,'"]'),y.QL);fa=this.iD(fa.querySelector("xfdf"),
"xfdf > fields","fields");z=z.split(".");this.r_(fa,z,0,y.value);y.sX=!0};ia.prototype.RKa=function(fa,z,y){null!==z&&(fa=this.jD(fa),fa=this.iD(fa,"pages"),this.ix(fa,'[number="'.concat(y+1,'"]'),z))};ia.prototype.OKa=function(fa,z){Object.keys(z).forEach(function(y){(y=fa.querySelector('annots [name="'.concat(y,'"]')))&&y.parentElement.removeChild(y)})};ia.prototype.r_=function(fa,z,y,n){if(y===z.length)z=document.createElementNS("","value"),z.textContent=n,this.ix(fa,"value",z);else{var e=z[y];
this.iD(fa,'[name="'.concat(e,'"]'),"field").setAttribute("name",e);fa=fa.querySelectorAll('[name="'.concat(e,'"]'));1===fa.length?this.r_(fa[0],z,y+1,n):(e=this.tBa(fa),this.r_(y===z.length-1?e:this.UVa(fa,e),z,y+1,n))}};ia.prototype.tBa=function(fa){for(var z=null,y=0;y<fa.length;y++){var n=fa[y];if(0===n.childElementCount||1===n.childElementCount&&"value"===n.children[0].tagName){z=n;break}}return z};ia.prototype.UVa=function(fa,z){for(var y=0;y<fa.length;y++)if(fa[y]!==z)return fa[y];return null};
ia.prototype.ix=function(fa,z,y){z=fa.querySelector(z);null!==z&&fa.removeChild(z);fa.appendChild(y)};ia.prototype.jD=function(fa){var z=fa.querySelector("pdf-info");if(null!==z)return z;z=this.iD(fa.querySelector("xfdf"),"pdf-info");z.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");z.setAttribute("version","2");z.setAttribute("import-version","4");return z};ia.prototype.iD=function(fa,z,y){var n=fa.querySelector(z);if(null!==n)return n;n=document.createElementNS("",y||z);fa.appendChild(n);
return n};return ia}();ua["default"]=ya},659:function(ya,ua){ya=function(){function h(){}h.prototype.RJ=function(ma){var na={pv:null,XU:null,Xs:{},ea:{}};ma=(new DOMParser).parseFromString(ma,"text/xml");na.pv=ma.querySelector("pdf-info calculation-order");na.XU=ma.querySelector("pdf-info document-actions");na.Xs=this.FMa(ma);na.ea=this.TMa(ma);return na};h.prototype.FMa=function(ma){var na=ma.querySelector("fields");ma=ma.querySelectorAll("pdf-info > ffield");if(null===na&&null===ma)return{};var oa=
{};this.ksa(oa,na);this.isa(oa,ma);return oa};h.prototype.ksa=function(ma,na){if(null!==na&&na.children){for(var oa=[],ja=0;ja<na.children.length;ja++){var ia=na.children[ja];oa.push({name:ia.getAttribute("name"),element:ia})}for(;0!==oa.length;)for(na=oa.shift(),ja=0;ja<na.element.children.length;ja++)ia=na.element.children[ja],"value"===ia.tagName?ma[na.name]={value:ia.textContent,QL:null,sX:!1}:ia.children&&oa.push({name:"".concat(na.name,".").concat(ia.getAttribute("name")),element:ia})}};h.prototype.isa=
function(ma,na){na.forEach(function(oa){var ja=oa.getAttribute("name");ma[ja]?ma[ja].QL=oa:ma[ja]={value:null,QL:oa,sX:!1}})};h.prototype.TMa=function(ma){var na=this,oa={};ma.querySelectorAll("pdf-info widget").forEach(function(ja){var ia=parseInt(ja.getAttribute("page"),10)-1;na.tN(oa,ia);oa[ia].Uka.push(ja)});ma.querySelectorAll("pdf-info page").forEach(function(ja){var ia=parseInt(ja.getAttribute("number"),10)-1;na.tN(oa,ia);oa[ia].page=ja});this.Baa(ma).forEach(function(ja){var ia=parseInt(ja.getAttribute("page"),
10),fa=ja.getAttribute("name");na.tN(oa,ia);oa[ia].fv[fa]=ja});this.gaa(ma).forEach(function(ja){var ia=parseInt(ja.getAttribute("page"),10);ja=ja.textContent;na.tN(oa,ia);oa[ia].l9[ja]=!0});return oa};h.prototype.tN=function(ma,na){ma[na]||(ma[na]={fv:{},l9:{},Uka:[],page:null})};return h}();ua.a=ya},670:function(ya,ua,h){var ma=h(0),na=h(1);h.n(na);ya=function(oa){function ja(ia){var fa=oa.call(this)||this;fa.$Aa=Array.isArray(ia)?ia:[ia];return fa}Object(ma.c)(ja,oa);ja.prototype.parse=function(){var ia=
this,fa={pv:null,XU:null,Xs:{},ea:{}};this.$Aa.forEach(function(z){fa=Object(na.merge)(fa,ia.RJ(z))});return fa};ja.prototype.Baa=function(ia){var fa=[];ia.querySelectorAll("add > *").forEach(function(z){fa.push(z)});ia.querySelectorAll("modify > *").forEach(function(z){fa.push(z)});return fa};ja.prototype.gaa=function(ia){return ia.querySelectorAll("delete > *")};return ja}(h(659).a);ua.a=ya},671:function(ya,ua,h){var ma=h(0);ya=function(na){function oa(ja){var ia=na.call(this)||this;ia.aBa=ja;return ia}
Object(ma.c)(oa,na);oa.prototype.parse=function(){return this.RJ(this.aBa)};oa.prototype.Baa=function(ja){return ja.querySelectorAll("annots > *")};oa.prototype.gaa=function(){return[]};return oa}(h(659).a);ua.a=ya}}]);}).call(this || window)
