/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{631:function(ya,ua,h){h.r(ua);h.d(ua,"ByteRangeRequest",function(){return w});var ma=h(0),na=h(1);h.n(na);var oa=h(2),ja=h(225);ya=h(134);var ia=h(371),fa=h(114),z=h(107),y=h(370),n=h(251);h=h(554);var e=[],a=[],f=window,r=function(){return function(){this.nr=1}}(),b;(function(ca){ca[ca.UNSENT=0]="UNSENT";ca[ca.DONE=4]="DONE"})(b||(b={}));var w=function(){function ca(ha,x,aa,ea){var pa=this;this.url=ha;this.range=x;this.Uf=aa;
this.withCredentials=ea;this.Qoa=b;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);f.Uint8Array&&(this.request.responseType="arraybuffer");ea&&(this.request.withCredentials=ea);ba.DISABLE_RANGE_HEADER||(Object(na.isUndefined)(x.stop)?this.request.setRequestHeader("Range","bytes=".concat(x.start)):this.request.setRequestHeader("Range",["bytes=",x.start,"-",x.stop-1].join("")));aa&&Object.keys(aa).forEach(function(la){pa.request.setRequestHeader(la,aa[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}ca.prototype.start=function(ha){var x=this,aa=this.request;aa.onreadystatechange=function(){if(x.aborted)return x.status=y.a.ABORTED,ha({code:y.a.ABORTED});if(this.readyState===x.Qoa.DONE){x.EM();var ea=0===window.document.URL.indexOf("file:///");200===aa.status||206===aa.status||ea&&0===aa.status?(ea=f.Xaa(this),x.u1(ea,ha)):(x.status=y.a.ERROR,
ha({code:x.status,status:x.status}))}};this.request.send(null);this.status=y.a.STARTED};ca.prototype.u1=function(ha,x){this.status=y.a.SUCCESS;if(x)return x(!1,ha)};ca.prototype.abort=function(){this.EM();this.aborted=!0;this.request.abort()};ca.prototype.EM=function(){var ha=Object(n.c)(this.url,this.range,a);-1!==ha&&a.splice(ha,1);if(0<e.length){ha=e.shift();var x=new ca(ha.url,ha.range,this.Uf,this.withCredentials);ha.request=x;a.push(ha);x.start(Object(n.d)(ha))}};ca.prototype.extend=function(ha){var x=
Object.assign({},this,ha.prototype);x.constructor=ha;return x};return ca}(),ba=function(ca){function ha(x,aa,ea,pa,la){ea=ca.call(this,x,ea,pa)||this;ea.Sm={};ea.BK=aa;ea.url=x;ea.DISABLE_RANGE_HEADER=!1;ea.NG=w;ea.e3=3;ea.Uf=la||{};return ea}Object(ma.c)(ha,ca);ha.prototype.KD=function(x,aa,ea){var pa=-1===x.indexOf("?")?"?":"&";switch(ea){case !1:case z.a.NEVER_CACHE:x="".concat(x+pa,"_=").concat(Object(na.uniqueId)());break;case !0:case z.a.CACHE:x="".concat(x+pa,"_=").concat(aa.start,",").concat(Object(na.isUndefined)(aa.stop)?
"":aa.stop)}return x};ha.prototype.P8=function(x,aa,ea,pa){void 0===ea&&(ea={});return new this.NG(x,aa,ea,pa)};ha.prototype.LAa=function(x,aa,ea,pa,la){for(var ka=0;ka<e.length;ka++)if(Object(na.isEqual)(e[ka].range,aa)&&Object(na.isEqual)(e[ka].url,x))return e[ka].xj.push(pa),e[ka].mO++,null;for(ka=0;ka<a.length;ka++)if(Object(na.isEqual)(a[ka].range,aa)&&Object(na.isEqual)(a[ka].url,x))return a[ka].xj.push(pa),a[ka].mO++,null;ea={url:x,range:aa,BK:ea,xj:[pa],mO:1};if(0===e.length&&a.length<this.e3)return a.push(ea),
ea.request=this.P8(x,aa,la,this.withCredentials),ea;e.push(ea);return null};ha.prototype.It=function(x,aa,ea){var pa=this.KD(x,aa,this.BK);(x=this.LAa(pa,aa,this.BK,ea,this.Uf))&&x.request.start(Object(n.d)(x));return function(){var la=Object(n.c)(pa,aa,a);if(-1!==la){var ka=--a[la].mO;0===ka&&a[la].request&&a[la].request.abort()}else la=Object(n.c)(pa,aa,e),-1!==la&&(ka=--e[la].mO,0===ka&&e.splice(la,1))}};ha.prototype.maa=function(){return{start:-ja.a}};ha.prototype.tGa=function(){var x=-(ja.a+
ja.e);return{start:x-ja.d,end:x}};ha.prototype.DA=function(x){var aa=this;this.MK=!0;var ea=ja.a;this.It(this.url,this.maa(),function(pa,la,ka){function ra(){var qa=aa.Ye.iaa();aa.It(aa.url,qa,function(sa,ta){if(sa)return Object(oa.i)("Error loading central directory: ".concat(sa)),x(sa);ta=Object(fa.a)(ta);if(ta.length!==qa.stop-qa.start)return x("Invalid XOD file: Zip central directory data is wrong size! Should be ".concat(qa.stop-qa.start," but is ").concat(ta.length));aa.Ye.nga(ta);aa.WT=!0;
aa.MK=!1;return x(!1)})}if(pa)return Object(oa.i)("Error loading end header: ".concat(pa)),x(pa,la,ka);la=Object(fa.a)(la);if(la.length!==ea)return x("Invalid XOD file: Zip end header data is wrong size!");try{aa.Ye=new ia.a(la)}catch(qa){return x(qa)}aa.Ye.OJa?aa.It(aa.url,aa.tGa(),function(qa,sa){if(qa)return Object(oa.i)("Error loading zip64 header: ".concat(qa)),x(qa);sa=Object(fa.a)(sa);aa.Ye.uKa(sa);ra()}):ra()})};ha.prototype.Raa=function(x){x(Object.keys(this.Ye.Ys))};ha.prototype.u_=function(x,
aa){var ea=this;if(this.Ye.v8(x)){var pa=this.Ye.EE(x);if(pa in this.Sm){var la=this.Yj[x];la.Zy=this.Sm[pa];la.Zy.nr++;la.cancel=la.Zy.cancel}else{var ka=this.Ye.vDa(x),ra=this.It(this.url,ka,function(sa,ta){sa?(Object(oa.i)('Error loading part "'.concat(x,'": ').concat(sa)),ea.It(ea.url,ka,function(wa,za){if(wa)return aa(wa,x);ea.rga(za,ka,pa,x,aa)})):ea.rga(ta,ka,pa,x,aa)}),qa=this.Yj[x];qa&&(qa.Jja=!0,qa.cancel=function(){qa.Zy.nr--;0===qa.Zy.nr&&(ra(),delete ea.Sm[pa])},this.Sm[pa]=new r(pa),
qa.Zy=this.Sm[pa],qa.Zy.cancel=qa.cancel)}}else delete this.Yj[x],aa(Error('File not found: "'.concat(x,'"')),x)};ha.prototype.rga=function(x,aa,ea,pa,la){if(x.length!==aa.stop-aa.start)la(Error("Part data is wrong size!"),pa);else{do{if(!this.Sm[ea])return;pa=this.Sm[ea].nr;for(var ka=aa.jx.length,ra=0;ra<ka;++ra){var qa=aa.jx[ra];la(!1,qa.bx,x["string"===typeof x?"substring":"subarray"](qa.start,qa.stop),this.Ye.zca(qa.bx));qa.bx in this.Yj&&delete this.Yj[qa.bx]}}while(pa!==this.Sm[ea].nr);delete this.Sm[ea]}};
ha.DISABLE_RANGE_HEADER=!1;ha.e3=3;return ha}(ya.a);(function(ca){function ha(x,aa,ea){var pa=ca.call(this)||this,la;for(la in x)pa[la]=x[la];pa.e1a=x;pa.startOffset=aa;pa.endOffset=ea;pa.P8=function(ka,ra,qa,sa){Object(na.isUndefined)(ra.stop)?(ra.start+=pa.endOffset,ra.stop=pa.endOffset):(ra.start+=pa.startOffset,ra.stop+=pa.startOffset);ka=pa.KD(pa.url,ra,pa.BK);return new x.NG(ka,ra,qa,sa)};return pa}Object(ma.c)(ha,ca);return ha})(ba);Object(h.a)(ba);Object(h.b)(ba);ua["default"]=ba}}]);}).call(this || window)
