/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[9],{645:function(ya,ua,h){function ma(aa){aa.ib();aa.advance();var ea=aa.current.textContent;aa.Hb();return ea}function na(aa){var ea=[];for(aa.ib();aa.advance();){var pa=aa.rb();"field"===pa?ea.push(String(aa.ka("name"))):Object(f.i)("unrecognised field list element: ".concat(pa))}aa.Hb();return ea}function oa(aa,ea){return ea?"false"!==aa:"true"===aa}function ja(aa,ea){var pa=aa.rb();switch(pa){case "javascript":return{name:"JavaScript",
javascript:aa.current.textContent};case "uri":return{name:"URI",uri:aa.ka("uri")};case "goto":pa=null;aa.ib();if(aa.advance()){var la=aa.ka("fit");pa={page:aa.ka("page"),fit:la};if("0"===pa.page)Object(f.i)("null page encountered in dest");else switch(ea=ea(Number(pa.page)),la){case "Fit":case "FitB":break;case "FitH":case "FitBH":pa.top=ea.Ba({x:0,y:aa.ka("top")||0}).y;break;case "FitV":case "FitBV":pa.left=ea.Ba({x:aa.ka("left")||0,y:0}).x;break;case "FitR":la=ea.Ba({x:aa.ka("left")||0,y:aa.ka("top")||
0});ea=ea.Ba({x:aa.ka("right")||0,y:aa.ka("bottom")||0});ea=new w.d(la.x,la.y,ea.x,ea.y);pa.top=ea.y1;pa.left=ea.x1;pa.bottom=ea.y2;pa.right=ea.x2;break;case "XYZ":la=ea.Ba({x:aa.ka("left")||0,y:aa.ka("top")||0});pa.top=la.y;pa.left=la.x;pa.zoom=aa.ka("zoom")||0;break;default:Object(f.i)("unknown dest fit: ".concat(la))}pa={name:"GoTo",dest:pa}}else Object(f.i)("missing dest in GoTo action");aa.Hb();return pa;case "submit-form":pa={name:"SubmitForm",url:aa.ka("url"),format:aa.ka("format"),method:aa.ka("method")||
"POST",exclude:oa(aa.ka("exclude"),!1)};ea=aa.ka("flags");pa.flags=ea?ea.split(" "):[];for(aa.ib();aa.advance();)switch(ea=aa.rb(),ea){case "fields":pa.fields=na(aa);break;default:Object(f.i)("unrecognised submit-form child: ".concat(ea))}aa.Hb();return pa;case "reset-form":pa={name:"ResetForm",exclude:oa(aa.ka("exclude"),!1)};for(aa.ib();aa.advance();)switch(ea=aa.rb(),ea){case "fields":pa.fields=na(aa);break;default:Object(f.i)("unrecognised reset-form child: ".concat(ea))}aa.Hb();return pa;case "hide":pa=
{name:"Hide",hide:oa(aa.ka("hide"),!0)};for(aa.ib();aa.advance();)switch(ea=aa.rb(),ea){case "fields":pa.fields=na(aa);break;default:Object(f.i)("unrecognised hide child: ".concat(ea))}aa.Hb();return pa;case "named":return{name:"Named",action:aa.ka("name")};default:Object(f.i)("Encountered unexpected action type: ".concat(pa))}return null}function ia(aa,ea,pa){var la={};for(aa.ib();aa.advance();){var ka=aa.rb();switch(ka){case "action":ka=aa.ka("trigger");if(ea?-1!==ea.indexOf(ka):1){la[ka]=[];for(aa.ib();aa.advance();){var ra=
ja(aa,pa);Object(r.isNull)(ra)||la[ka].push(ra)}aa.Hb()}else Object(f.i)("encountered unexpected trigger on field: ".concat(ka));break;default:Object(f.i)("encountered unknown action child: ".concat(ka))}}aa.Hb();return la}function fa(aa){return new ba.a(aa.ka("r")||0,aa.ka("g")||0,aa.ka("b")||0,aa.ka("a")||1)}function z(aa,ea){var pa=aa.ka("name"),la=aa.ka("type")||"Type1",ka=aa.ka("size"),ra=ea.Ba({x:0,y:0});ka=ea.Ba({x:Number(ka),y:0});ea=ra.x-ka.x;ra=ra.y-ka.y;pa={name:pa,type:la,size:Math.sqrt(ea*
ea+ra*ra)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(aa.ib();aa.advance();)switch(la=aa.rb(),la){case "stroke-color":pa.strokeColor=fa(aa);break;case "fill-color":pa.fillColor=fa(aa);break;default:Object(f.i)("unrecognised font child: ".concat(la))}aa.Hb();return pa}function y(aa){var ea=[];for(aa.ib();aa.advance();){var pa=aa.rb();switch(pa){case "option":pa=ea;var la=pa.push;var ka=aa;ka={value:ka.ka("value"),displayValue:ka.ka("display-value")||void 0};la.call(pa,ka);break;default:Object(f.i)("unrecognised options child: ".concat(pa))}}aa.Hb();
return ea}function n(aa,ea){var pa=aa.ka("name"),la={type:aa.ka("type"),quadding:aa.ka("quadding")||"Left-justified",maxLen:aa.ka("max-len")||-1},ka=aa.ka("flags");Object(r.isString)(ka)&&(la.flags=ka.split(" "));for(aa.ib();aa.advance();)switch(ka=aa.rb(),ka){case "actions":la.actions=ia(aa,["C","F","K","V"],function(){return ea});break;case "default-value":la.defaultValue=ma(aa);break;case "font":la.font=z(aa,ea);break;case "options":la.options=y(aa);break;default:Object(f.i)("unknown field child: ".concat(ka))}aa.Hb();
return new window.da.Annotations.la.xa(pa,la)}function e(aa,ea){switch(aa.type){case "Tx":try{if(Object(ha.c)(aa.actions))return new b.a.DatePickerWidgetAnnotation(aa,ea)}catch(pa){Object(f.i)(pa)}return new b.a.TextWidgetAnnotation(aa,ea);case "Ch":return aa.flags.get(x.WidgetFlags.COMBO)?new b.a.ChoiceWidgetAnnotation(aa,ea):new b.a.ListWidgetAnnotation(aa,ea);case "Btn":return aa.flags.get(x.WidgetFlags.PUSH_BUTTON)?new b.a.PushButtonWidgetAnnotation(aa,ea):aa.flags.get(x.WidgetFlags.RADIO)?new b.a.RadioButtonWidgetAnnotation(aa,
ea):new b.a.CheckButtonWidgetAnnotation(aa,ea);case "Sig":return new b.a.SignatureWidgetAnnotation(aa,ea);default:Object(f.i)("Unrecognised field type: ".concat(aa.type))}return null}function a(aa,ea,pa,la){var ka=[],ra={};aa.ib();var qa=[],sa={},ta=[];Object(ca.a)(function(){if(aa.advance()){var wa=aa.rb();switch(wa){case "calculation-order":qa="calculation-order"===aa.rb()?na(aa):[];break;case "document-actions":sa=ia(aa,["Init","Open"],ea);break;case "pages":wa=[];for(aa.ib();aa.advance();){var za=
aa.rb();switch(za){case "page":za=wa;var Ca=za.push,Ea=aa,Ba=ea,Aa={number:Ea.ka("number")};for(Ea.ib();Ea.advance();){var Ha=Ea.rb();switch(Ha){case "actions":Aa.actions=ia(Ea,["O","C"],Ba);break;default:Object(f.i)("unrecognised page child: ".concat(Ha))}}Ea.Hb();Ca.call(za,Aa);break;default:Object(f.i)("unrecognised page child: ".concat(za))}}aa.Hb();ta=wa;break;case "field":za=n(aa,ea(1));ra[za.name]=za;break;case "widget":wa={border:{style:"Solid",width:1},backgroundColor:[],fieldName:aa.ka("field"),
page:aa.ka("page"),index:aa.ka("index")||0,rotation:aa.ka("rotation")||0,flags:[],isImporting:!0};(za=aa.ka("appearance"))&&(wa.appearance=za);(za=aa.ka("flags"))&&(wa.flags=za.split(" "));for(aa.ib();aa.advance();)switch(za=aa.rb(),za){case "rect":Ca=aa;Ea=ea(Number(wa.page));za=Ea.Ba({x:Ca.ka("x1")||0,y:Ca.ka("y1")||0});Ca=Ea.Ba({x:Ca.ka("x2")||0,y:Ca.ka("y2")||0});za=new w.d(za.x,za.y,Ca.x,Ca.y);za.normalize();wa.rect={x1:za.x1,y1:za.y1,x2:za.x2,y2:za.y2};break;case "border":za=aa;Ca={style:za.ka("style")||
"Solid",width:za.ka("width")||1,color:[0,0,0]};for(za.ib();za.advance();)switch(Ea=za.rb(),Ea){case "color":Ca.color=fa(za);break;default:Object(f.i)("unrecognised border child: ".concat(Ea))}za.Hb();wa.border=Ca;break;case "background-color":wa.backgroundColor=fa(aa);break;case "actions":wa.actions=ia(aa,"E X D U Fo Bl PO PC PV PI".split(" "),ea);break;case "appearances":za=aa;Ca=Object(ha.b)(wa,"appearances");for(za.ib();za.advance();)if(Ea=za.rb(),"appearance"===Ea){Ea=za.ka("name");Ba=Object(ha.b)(Ca,
Ea);Ea=za;for(Ea.ib();Ea.advance();)switch(Aa=Ea.rb(),Aa){case "Normal":Object(ha.b)(Ba,"Normal").data=Ea.current.textContent;break;default:Object(f.i)("unexpected appearance state: ",Aa)}Ea.Hb()}else Object(f.i)("unexpected appearances child: ".concat(Ea));za.Hb();break;case "extra":za=aa;Ca=ea;Ea={};for(za.ib();za.advance();)switch(Ba=za.rb(),Ba){case "font":Ea.font=z(za,Ca(1));break;default:Object(f.i)("unrecognised extra child: ".concat(Ba))}za.Hb();za=Ea;za.font&&(wa.font=za.font);break;case "captions":Ca=
aa;za={};(Ea=Ca.ka("Normal"))&&(za.Normal=Ea);(Ea=Ca.ka("Rollover"))&&(za.Rollover=Ea);(Ca=Ca.ka("Down"))&&(za.Down=Ca);wa.captions=za;break;default:Object(f.i)("unrecognised widget child: ".concat(za))}aa.Hb();(za=ra[wa.fieldName])?(wa=e(za,wa),ka.push(wa)):Object(f.i)("ignoring widget with no corresponding field data: ".concat(wa.fieldName));break;default:Object(f.i)("Unknown element encountered in PDFInfo: ".concat(wa))}return!0}return!1},function(){aa.Hb();pa({calculationOrder:qa,widgets:ka,fields:ra,
documentActions:sa,pages:ta,custom:[]})},la)}h.r(ua);h.d(ua,"parse",function(){return a});var f=h(2),r=h(1);h.n(r);var b=h(173),w=h(4),ba=h(11),ca=h(26),ha=h(148),x=h(18)}}]);}).call(this || window)
