/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{640:function(ya,ua,h){h.r(ua);var ma=h(0),na=h(1);h.n(na);var oa=h(2),ja=h(225);ya=h(53);var ia=h(134),fa=h(371),z=h(107),y=h(370);h=h(554);var n=window,e=function(){function r(b,w,ba){var ca=-1===b.indexOf("?")?"?":"&";switch(w){case z.a.NEVER_CACHE:this.url="".concat(b+ca,"_=").concat(Object(na.uniqueId)());break;default:this.url=b}this.Uf=ba;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}r.prototype.start=function(b,w){var ba=this,ca=this,ha=this.request,x;ca.OF=0;b&&Object.keys(b).forEach(function(aa){ba.request.setRequestHeader(aa,b[aa])});w&&(this.request.withCredentials=w);this.TO=setInterval(function(){var aa=0===window.document.URL.indexOf("file:///");aa=200===ha.status||
aa&&0===ha.status;if(ha.readyState!==y.b.DONE||aa){try{ha.responseText}catch(ea){return}ca.OF<ha.responseText.length&&(x=ca.hOa())&&ca.trigger(r.Events.DATA,[x]);0===ha.readyState&&(clearInterval(ca.TO),ca.trigger(r.Events.DONE))}else clearInterval(ca.TO),ca.trigger(r.Events.DONE,["Error received return status ".concat(ha.status)])},1E3);this.request.send(null);this.status=y.a.STARTED};r.prototype.hOa=function(){var b=this.request,w=b.responseText;if(0!==w.length)if(this.OF===w.length)clearInterval(this.TO),
this.trigger(r.Events.DONE);else return w=Math.min(this.OF+3E6,w.length),b=n.Xaa(b,this.OF,!0,w),this.OF=w,b};r.prototype.abort=function(){clearInterval(this.TO);var b=this;this.request.onreadystatechange=function(){Object(oa.i)("StreamingRequest aborted");b.status=y.a.ABORTED;return b.trigger(r.Events.ABORTED)};this.request.abort()};r.prototype.finish=function(){var b=this;this.request.onreadystatechange=function(){b.status=y.a.SUCCESS;return b.trigger(r.Events.DONE)};this.request.abort()};r.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return r}();Object(ya.a)(e);var a;(function(r){r[r.LOCAL_HEADER=0]="LOCAL_HEADER";r[r.FILE=1]="FILE";r[r.CENTRAL_DIR=2]="CENTRAL_DIR"})(a||(a={}));var f=function(r){function b(){var w=r.call(this)||this;w.buffer="";w.state=a.LOCAL_HEADER;w.j1=4;w.Vq=null;w.KA=ja.c;w.Ys={};return w}Object(ma.c)(b,r);b.prototype.TNa=function(w){var ba;for(w=this.buffer+w;w.length>=this.KA;)switch(this.state){case a.LOCAL_HEADER:this.Vq=ba=this.mOa(w.slice(0,this.KA));if(ba.yB!==
ja.g)throw Error("Wrong signature in local header: ".concat(ba.yB));w=w.slice(this.KA);this.state=a.FILE;this.KA=ba.DT+ba.Sw+ba.gE+this.j1;this.trigger(b.Events.HEADER,[ba]);break;case a.FILE:this.Vq.name=w.slice(0,this.Vq.Sw);this.Ys[this.Vq.name]=this.Vq;ba=this.KA-this.j1;var ca=w.slice(this.Vq.Sw+this.Vq.gE,ba);this.trigger(b.Events.FILE,[this.Vq.name,ca,this.Vq.iU]);w=w.slice(ba);if(w.slice(0,this.j1)===ja.h)this.state=a.LOCAL_HEADER,this.KA=ja.c;else return this.state=a.CENTRAL_DIR,!0}this.buffer=
w;return!1};b.Events={HEADER:"header",FILE:"file"};return b}(fa.a);Object(ya.a)(f);ya=function(r){function b(w,ba,ca,ha,x){ca=r.call(this,w,ca,ha)||this;ca.url=w;ca.stream=new e(w,ba);ca.Ye=new f;ca.Ifa=window.createPromiseCapability();ca.yga={};ca.Uf=x;return ca}Object(ma.c)(b,r);b.prototype.XG=function(w){var ba=this;this.request([this.pn,this.up,this.nn]);this.stream.addEventListener(e.Events.DATA,function(ca){try{if(ba.Ye.TNa(ca))return ba.stream.finish()}catch(ha){throw ba.stream.abort(),ba.Vv(ha),
w(ha),ha;}});this.stream.addEventListener(e.Events.DONE,function(ca){ba.lNa=!0;ba.Ifa.resolve();ca&&(ba.Vv(ca),w(ca))});this.Ye.addEventListener(f.Events.HEADER,Object(na.bind)(this.xga,this));this.Ye.addEventListener(f.Events.FILE,Object(na.bind)(this.EOa,this));return this.stream.start(this.Uf,this.withCredentials)};b.prototype.Raa=function(w){var ba=this;this.Ifa.promise.then(function(){w(Object.keys(ba.Ye.Ys))})};b.prototype.Yt=function(){return!0};b.prototype.request=function(w){var ba=this;
this.lNa&&w.forEach(function(ca){ba.yga[ca]||ba.mWa(ca)})};b.prototype.xga=function(){};b.prototype.abort=function(){this.stream&&this.stream.abort()};b.prototype.mWa=function(w){this.trigger(ia.a.Events.PART_READY,[{Qb:w,error:"Requested part not found",dm:!1,Gi:!1}])};b.prototype.EOa=function(w,ba,ca){this.yga[w]=!0;this.trigger(ia.a.Events.PART_READY,[{Qb:w,data:ba,dm:!1,Gi:!1,error:null,Je:ca}])};return b}(ia.a);Object(h.a)(ya);Object(h.b)(ya);ua["default"]=ya}}]);}).call(this || window)
