/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[13],{642:function(ya,ua,h){function ma(){return!1}function na(ba,ca,ha){if(!(ca in w))return!0;ca=w[ca];for(var x=0;x<ca.length;x++){var aa=ba;var ea=ca[x];var pa=ha;if(ea.name in aa){var la="",ka=!1;aa=aa[ea.name];switch(ea.type){case "s":la="String";ka=Object(ia.isString)(aa);break;case "a":la="Array";ka=Object(ia.isArray)(aa);break;case "n":la="Number";ka=Object(ia.isNumber)(aa)&&Object(ia.isFinite)(aa);break;case "o":la="Object",
ka=Object(ia.isObject)(aa)&&!Object(ia.isArray)(aa)}ka||pa.reject('Expected response field "'.concat(ea.name,'" to have type ').concat(la));ea=ka}else pa.reject('Response missing field "'.concat(ea.name,'"')),ea=!1;if(!ea)return!1}return!0}function oa(ba){for(var ca=0,ha=["locale","excelMaxAllowedCellCount","applyPageBreaksToSheet","excelDefaultCellBorderWidth","displayChangeTracking"];ca<ha.length;ca++){var x=ha[ca],aa=x;x=x.charAt(0).toUpperCase()+x.slice(1);ba[aa]&&(Object.defineProperty(ba,x,
Object.getOwnPropertyDescriptor(ba,aa)),delete ba[aa])}return ba}h.r(ua);var ja=h(0),ia=h(1);h.n(ia);var fa=h(2);ya=h(53);var z=h(37),y=h(661),n=h(134),e=h(554),a=h(52),f=h(251),r=function(){function ba(){this.request=this.result=null;this.state=0;var ca=this;ca.promise=new Promise(function(ha,x){ca.resolve=function(){if(0===ca.state||4===ca.state)ca.state=1,ca.result=arguments[0],ha.apply(null,arguments)};ca.reject=function(){if(0===ca.state||4===ca.state)ca.state=2,x.apply(null,arguments)}})}ba.prototype.Mo=
function(){return 1===(this.state&1)};ba.prototype.oJa=function(){return 2===(this.state&2)};ba.prototype.Dm=function(){return!this.oJa()&&!this.Mo()};ba.prototype.DIa=function(){return 4===(this.state&4)};ba.prototype.G0=function(){this.state|=4};return ba}(),b=function(){function ba(){this.iA={};this.Mc=[]}ba.prototype.pop=function(){var ca=this.Mc.pop();this.iA[ca.key]=void 0;return ca};ba.prototype.push=function(ca,ha){ha={key:ca,data:ha};this.Mc.push(ha);this.iA[ca]=ha.data};ba.prototype.contains=
function(ca){return!!this.iA[ca]};ba.prototype.get=function(ca){return this.iA[ca]};ba.prototype.set=function(ca,ha){var x=this;this.iA[ca]=ha;this.Mc.forEach(function(aa,ea){aa.key===ca&&(x.Mc[ea]=aa)})};ba.prototype.remove=function(ca){var ha=this;this.iA[ca]=void 0;this.Mc.forEach(function(x,aa){x.key===ca&&ha.Mc.splice(aa,1)})};ba.prototype.length=function(){return this.Mc.length};return ba}(),w={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",
type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};h=function(){function ba(ca,ha,x){var aa=this;this.l1=this.t9=!1;this.Xj=this.FQ=this.ZB=
this.zg=this.uD=this.Mt=this.tD=this.Lr=null;this.er=new r;this.xv=new r;this.$K=!1;this.Sh=this.Eg=this.Fg=this.Gh=null;this.ti=[];this.WL=[];this.cache={};this.timeStamp=0;this.Rj=[];this.Nm=[];this.wV=null;this.f9=!1;this.Wha=this.id=null;this.NY=this.Yba=ma;this.ji=0;this.nX=!1;this.qea=1;this.Jm={};this.Ly=0;this.hB=new b;ha.endsWith("/")||(ha+="/");x=x||{};this.t9=x.disableWebsockets||!1;this.l1=x.singleServerMode||!1;null!=x.customQueryParameters&&Object(a.b)("wvsQueryParameters",x.customQueryParameters);
ha.endsWith("blackbox/")||(ha+="blackbox/");this.Lr=x.uploadData||null;this.ZB=x.uriData||null;this.tD=x.cacheKey||null;if(this.Mt=x.officeOptions||null)this.Mt=oa(this.Mt);this.zg=x.rasterizerOptions||null;this.uD=x.cadOptions||null;this.Yg=ha;this.WU=ca;this.eu(!0);this.fz=(new y.a(ha,null,this.Vk())).YBa(!this.t9,function(ea){aa.TLa(ea)},function(){return null},function(){aa.$K=!1},function(){aa.zQa()})}ba.prototype.Fxa=function(){var ca=this;return new Promise(function(ha,x){var aa=new XMLHttpRequest,
ea="".concat(ca.Yg,"ck");aa.open("GET",ea);aa.withCredentials=ca.Vk();aa.onreadystatechange=function(){aa.readyState===XMLHttpRequest.DONE&&(200===aa.status?ha():x())};aa.send()})};ba.prototype.SSa=function(ca){this.Yba=ca||ma;this.NY=ma};ba.prototype.jva=function(){this.mha();return this.fz.Rv()};ba.prototype.mha=function(){Object(ja.b)(this,void 0,void 0,function(){return Object(ja.d)(this,function(ca){switch(ca.label){case 0:return this.xv=new r,this.er=new r,this.$K=!1,this.id=null,this.f9=!1,
[4,this.Fxa().catch(function(){})];case 1:return ca.aa(),[2]}})})};ba.prototype.zQa=function(){this.Yba();this.mha();this.Gh&&(this.Gh.Dm()?this.bk(this.Gh.request):this.Gh.Mo()&&this.NY(this.Gh.result.url,"pdf")&&(this.Gh=null,this.jha()));this.Sh&&this.Sh.Dm()&&this.bk(this.Sh.request);this.Fg&&this.Fg.Dm()?this.bk(this.Fg.request):this.Eg&&this.Eg.Dm()&&this.zba();var ca;for(ca=0;ca<this.Rj.length;ca++)this.Rj[ca]&&(this.Rj[ca].Dm()?this.bk(this.Rj[ca].request):this.Rj[ca].Mo()&&this.NY(this.Rj[ca].result.url,
"image")&&(this.Rj[ca]=null,this.iP(Object(ia.uniqueId)(),ca)));for(ca=0;ca<this.Nm.length;ca++)this.Nm[ca]&&this.Nm[ca].Dm()&&!this.Nm[ca].DIa()&&this.bk(this.Nm[ca].request);for(ca=0;ca<this.ti.length;ca++)this.ti[ca]&&this.ti[ca].Dm()&&this.bk(this.ti[ca].request)};ba.prototype.JHa=function(){return this.$K?Promise.resolve():(this.$K=!0,this.timeStamp=Date.now(),this.fz.uN())};ba.prototype.eXa=function(){var ca=this,ha,x,aa,ea,pa;return new Promise(function(la,ka){if(ca.Lr)ha=new FormData,ha.append("file",
ca.Lr.fileHandle,ca.Lr.fileHandle.name),ca.Mt&&ha.append("officeOptions",JSON.stringify(ca.Mt)),ca.zg&&ha.append("rasterizerOptions",JSON.stringify(ca.zg)),ca.uD&&ha.append("cadOptions",ca.uD.getJsonString()),ca.tD&&ha.append("cacheKey",ca.tD),x=ca.Lr.loadCallback,ea="upload",aa=ca.Lr.extension;else if(ca.ZB)ha={uri:ca.ZB.uri,F1a:ca.ZB.shareId},ha=Object.keys(ha).map(function(sa){return"".concat(sa,"=").concat(ha[sa]?encodeURIComponent(ha[sa]):"")}).join("&"),pa="application/x-www-form-urlencoded; charset=UTF-8",
x=ca.ZB.loadCallback,ea="url",aa=ca.ZB.extension;else{la();return}var ra=new XMLHttpRequest,qa=Object(z.l)(ca.Yg,"AuxUpload");qa=Object(f.a)(qa,{type:ea,ext:aa});ra.open("POST",qa);ra.withCredentials=ca.Vk();pa&&ra.setRequestHeader("Content-Type",pa);ra.addEventListener("load",function(){if(ra.readyState===ra.DONE&&200===ra.status){var sa=JSON.parse(ra.response);ca.WU=sa.uri;x(sa);la(sa)}});ra.addEventListener("error",function(){ka("".concat(ra.statusText," ").concat(JSON.stringify(ra)))});ca.Lr&&
null!=ca.Lr.onProgress&&(ra.upload.onprogress=function(sa){ca.Lr.onProgress(sa)});ra.send(ha)})};ba.prototype.lQa=function(ca){this.password=ca||null;this.er.Mo()||(this.er=new r,this.bk({t:"pages"}));return this.er.promise};ba.prototype.XG=function(ca){this.wV=ca||null;this.er.Mo()||this.bk({t:"pages"});return this.er.promise};ba.prototype.FD=function(ca){ca=Object.assign(ca,{uri:encodeURIComponent(this.WU)});this.wV&&(ca.ext=this.wV);this.Xj&&(ca.c=this.Xj);this.password&&(ca.pswd=this.password);
this.tD&&(ca.cacheKey=this.tD);this.Mt&&(ca.officeOptions=this.Mt);this.zg&&(ca.rastOptions=this.zg);this.uD&&(ca.cadOptions=this.uD.mImpl);return ca};ba.prototype.qRa=function(){0<this.hB.length()&&10>=this.Ly&&this.rRa(this.hB.pop().data)};ba.prototype.sua=function(ca){0<this.hB.length()&&this.hB.contains(ca)&&this.hB.remove(ca)};ba.prototype.bk=function(ca){ca=this.FD(ca);this.fz.send(ca)};ba.prototype.Sha=function(ca,ha){10<this.Ly?this.hB.push(ca,ha):(this.Ly++,ca=this.FD(ha),this.fz.send(ca))};
ba.prototype.rRa=function(ca){this.Ly++;ca=this.FD(ca);this.fz.send(ca)};ba.prototype.$p=function(ca){return ca};ba.prototype.Xba=function(ca){this.l1&&ca?Object(fa.i)("Server failed health check. Single server mode ignoring check."):!this.P_a&&ca&&3>=this.ji?(this.nX=!0,this.fz.Rv()):3<this.ji&&(this.l1=!0)};ba.prototype.TLa=function(ca){var ha=this,x=ca.data,aa=ca.err,ea=ca.t;switch(ea){case "upload":aa?this.fXa.reject(aa):this.fXa.resolve("Success");break;case "pages":aa?this.er.reject(aa):na(x,
ea,this.er)&&this.er.resolve(x);break;case "config":if(aa)this.xv.reject(aa);else if(na(x,ea,this.xv)){this.Xba(x.unhealthy);x.id&&(this.id=x.id);if(x.auth){var pa=Object(a.a)("wvsQueryParameters");pa.auth=x.auth;Object(a.b)("wvsQueryParameters",pa)}x.serverVersion&&(this.FQ=x.serverVersion,Object(fa.g)("[WebViewer Server] server version: ".concat(this.FQ)));x.serverID?(this.ji=x.serverID===this.Wha&&this.nX?this.ji+1:0,this.Wha=x.serverID):this.ji=0;this.nX=!1;this.xv.resolve(x)}break;case "health":aa?
this.xv.reject(aa):na(x,ea,this.xv)&&this.Xba(x.unhealthy);break;case "pdf":x.url=Object(f.a)("".concat(this.Yg,"../").concat(encodeURI(x.url)));aa?this.Gh.reject(aa):na(x,ea,this.Gh)&&this.Gh.resolve(x);break;case "ApString2Xod":x.url=Object(f.a)("".concat(this.Yg,"../data/").concat(encodeURI(x.url)));aa?this.Jm[x.rID].reject(aa):na(x,ea,this.Jm[x.rID])&&this.Jm[x.rID].resolve(x);break;case "docmod":x.url=Object(f.a)("".concat(this.Yg,"../").concat(encodeURI(x.url)));aa?this.Jm[x.rID].reject(aa):
na(x,ea,this.Gh)&&this.Jm[x.rID].resolve(x);break;case "xod":if(aa)this.Fg&&this.Fg.Dm()&&this.Fg.reject(aa),this.Eg&&this.Eg.Dm()&&this.Eg.reject(aa);else if(x.notFound)x.noCreate||this.Fg&&this.Fg.Dm()&&this.Fg.resolve(x),this.Eg&&this.Eg.Dm()&&this.Eg.resolve(x);else{x.url&&(x.url=Object(f.a)("".concat(this.Yg,"../").concat(encodeURI(x.url))));if(!this.Eg||this.Eg.Mo())this.Eg=new r,this.Eg.request={t:"xod",noCreate:!0};this.Fg||(this.Fg=new r,this.Fg.request={t:"xod"});this.Eg.resolve(x);this.Fg.resolve(x)}break;
case "cAnnots":pa=this.Sh;if(aa)pa.reject(aa);else if(na(x,ea,pa)){pa.G0();var la=[],ka=x.annots;x=function(za){var Ca=ka[za].s,Ea=ka[za].e,Ba="".concat(ra.Yg,"../").concat(encodeURI(ka[za].xfdf)),Aa="true"===ka[za].hasAppearance?Object(f.a)("".concat(Ba,".xodapp")):null,Ha=Object(ia.range)(Ca,Ea);la[za]={range:Ha,promise:new Promise(function(Na,La){var Qa=new XMLHttpRequest;Qa.open("GET",Object(f.a)(Ba));Qa.responseType="text";Qa.withCredentials=ha.Vk();Qa.addEventListener("load",function(){Qa.readyState===
Qa.DONE&&200===Qa.status&&Na({Pr:Qa.response,Pp:Aa,range:Ha})});Qa.addEventListener("error",function(){La("".concat(Qa.statusText," ").concat(JSON.stringify(Qa)))});Qa.send()})}};var ra=this;for(aa=0;aa<ka.length;aa++)x(aa);pa.resolve(la)}break;case "annots":if(aa)this.Sh.reject(aa);else if(na(x,ea,this.Sh)){this.Sh.G0();var qa=new XMLHttpRequest;pa="".concat(this.Yg,"../").concat(encodeURI(x.url));var sa=x.hasAppearance?Object(f.a)("".concat(pa,".xodapp")):null;qa.open("GET",Object(f.a)(pa));qa.responseType=
"text";qa.withCredentials=this.Vk();qa.addEventListener("load",function(){qa.readyState===qa.DONE&&200===qa.status&&ha.Sh.resolve({Pr:qa.response,Pp:sa})});qa.addEventListener("error",function(){ha.Sh.reject("".concat(qa.statusText," ").concat(JSON.stringify(qa)))});qa.send()}break;case "image":this.Ly--;var ta=this.Rj[x.p];aa?ta.promise.reject(aa):na(x,ea,ta)&&(ta.result=x,ta.result.url=Object(f.a)("".concat(this.Yg,"../").concat(encodeURI(ta.result.url))),ta.resolve(ta.result));break;case "tiles":this.Ly--;
ta=x.rID;pa=this.ti[ta];this.ti[ta]=null;this.WL.push(ta);if(aa)pa.reject(aa);else if(na(x,ea,pa)){for(aa=0;aa<x.tiles.length;aa++)x.tiles[aa]=Object(f.a)("".concat(this.Yg,"../").concat(encodeURI(x.tiles[aa])));pa.resolve(x)}break;case "text":ta=this.Nm[x.p];if(aa)ta.reject(aa);else if(na(x,ea,ta)){ta.G0();var wa=new XMLHttpRequest;x=Object(f.a)("".concat(this.Yg,"../").concat(encodeURI(x.url)));wa.open("GET",x);wa.withCredentials=this.Vk();wa.addEventListener("load",function(){wa.readyState===wa.DONE&&
200===wa.status&&(ta.result=JSON.parse(wa.response),ta.resolve(ta.result))});wa.addEventListener("error",function(za){ta.reject("".concat(wa.statusText," ").concat(JSON.stringify(za)))});wa.send()}break;case "progress":"loading"===x.t&&this.trigger(n.a.Events.DOCUMENT_LOADING_PROGRESS,[x.bytes,x.total])}this.qRa();!ea&&ca.echo&&ca&&"apstring2xod"===ca.echo.t&&(ca=ca.echo.reqID)&&(2<=parseInt(this.FQ,10)?this.Jm[ca].reject("Message unhandled by server"):this.Jm[ca].reject())};ba.prototype.LCa=function(){return Object(ja.b)(this,
void 0,void 0,function(){return Object(ja.d)(this,function(ca){switch(ca.label){case 0:return[4,this.JHa()];case 1:return ca.aa(),[2,this.xv.promise]}})})};ba.prototype.mCa=function(ca){for(var ha=this,x=new XMLHttpRequest,aa=Object(f.a)("".concat(this.Yg,"aul"),{id:this.id}),ea=new FormData,pa={},la=0;la<ca.body.length;la++){var ka=ca.body[la];pa[ka.id]="".concat(ka.iT.w,";").concat(ka.iT.h);ea.append(ka.id,ka.iT.dataString)}ca={t:"apstring2xod",reqID:this.qea++,parts:pa};var ra=this.FD(ca);ea.append("msg",
JSON.stringify(ra));this.Jm[ra.reqID]=new r;x.open("POST",aa);x.withCredentials=this.Vk;aa=new Promise(function(qa,sa){x.onreadystatechange=function(){4===x.readyState&&(200===x.status?qa():sa("An error occurred while sending down appearance strings to the server"))}});x.send(ea);return aa.then(function(){return ha.Jm[ra.reqID].promise})};ba.prototype.ova=function(){var ca=this.FQ.split("-")[0].split("."),ha=["1","5","9"];if(3!==ca.length)throw Error("Invalid WVS version length.");if(3!==ha.length)throw Error("Invalid version length.");
for(var x=0;x<ca.length;++x){if(ha.length===x||ca[x]>ha[x])return-1;if(ca[x]!==ha[x])return 1}return 0};ba.prototype.tv=function(){return 0>=this.ova()};ba.prototype.NV=function(){this.Sh||(this.Sh=new r,this.tv()?this.Sh.request={t:"cAnnots"}:this.Sh.request={t:"annots"},this.bk(this.Sh.request));return this.Sh.promise};ba.prototype.iP=function(ca,ha){this.Rj[ha]||(this.Rj[ha]=new r,this.Rj[ha].request={t:"image",p:ha},this.Sha(ca,this.Rj[ha].request));return this.Rj[ha].promise};ba.prototype.mQa=
function(ca){this.Nm[ca]||(this.Nm[ca]=new r,this.Nm[ca].request={t:"text",p:ca},this.bk(this.Nm[ca].request));return this.Nm[ca].promise};ba.prototype.nQa=function(ca,ha,x,aa,ea){var pa=this.ti.length;this.WL.length&&(pa=this.WL.pop());this.ti[pa]=new r;this.ti[pa].request={t:"tiles",p:ha,z:x,r:aa,size:ea,rID:pa};this.Sha(ca,this.ti[pa].request);return this.ti[pa].promise};ba.prototype.jha=function(){this.Gh||(this.Gh=new r,this.Gh.request={t:"pdf"},this.f9?this.Gh.resolve({url:this.WU}):this.bk(this.Gh.request));
return this.Gh.promise};ba.prototype.Daa=function(ca){var ha=this,x=new XMLHttpRequest,aa=Object(f.a)("".concat(this.Yg,"aul"),{id:this.id}),ea=new FormData,pa={};ca.annots&&(pa.annots="xfdf");ca.watermark&&(pa.watermark="png");ca.redactions&&(pa.redactions="redact");pa={t:"docmod",reqID:this.qea++,parts:pa};ca.print&&(pa.print=!0);var la=this.FD(pa);ea.append("msg",JSON.stringify(la));return Promise.all([ca.annots,ca.watermark,ca.redactions].map(function(ka){return Promise.resolve(ka)})).then(function(ka){var ra=
ka[0],qa=ka[1];ka=ka[2];ra&&ea.append("annots",ra);qa&&ea.append("watermark",qa);ka&&ea.append("redactions",ka);ha.Jm[la.reqID]=new r;x.open("POST",aa);x.withCredentials=ha.Vk;ra=new Promise(function(sa,ta){x.onreadystatechange=function(){4===x.readyState&&(200===x.status?sa():ta("An error occurred while sending down annotation data to the server"))}});x.send(ea);return ra.then(function(){return ha.Jm[la.reqID].promise})})};ba.prototype.zba=function(){this.Eg||(this.Eg=new r,this.Eg.request={t:"xod",
noCreate:!0},this.bk(this.Eg.request));return this.Eg.promise};ba.prototype.oQa=function(){this.Fg||(this.Fg=new r,this.Fg.request={t:"xod"},this.bk(this.Fg.request));return this.Fg.promise};ba.prototype.Yt=function(){return!0};ba.prototype.request=function(){};ba.prototype.xga=function(){};ba.prototype.abort=function(){for(var ca=0;ca<this.ti.length;ca++)this.ti[ca]&&(this.ti[ca].resolve(null),this.ti[ca]=null,this.WL.push(ca));this.close()};ba.prototype.EP=function(ca){this.Xj=this.Xj||{};this.Xj.headers=
ca};ba.prototype.eu=function(ca){this.Xj=this.Xj||{};this.Xj.internal=this.Xj.internal||{};this.Xj.internal.withCredentials=ca};ba.prototype.Vk=function(){return this.Xj&&this.Xj.internal?this.Xj.internal.withCredentials:null};ba.prototype.getFileData=function(){return Promise.reject()};return ba}();Object(ya.a)(h);Object(e.a)(h);Object(e.b)(h);ua["default"]=h},661:function(ya,ua,h){var ma=h(0),na=h(2),oa=h(37),ja=h(52),ia=h(251),fa=h(110),z=function(){function n(e,a,f,r,b,w){void 0===f&&(f=null);
void 0===r&&(r=null);void 0===b&&(b=null);void 0===w&&(w=null);this.qX=!1;this.ji=0;this.UF=8;this.zha=3E3;this.$P=!1;this.u7=this.IXa(e);this.url=a?"".concat(this.u7,"/").concat(a):"".concat(this.u7,"/ws");this.DU=f;this.nG=r;this.DD=b;this.kha=w}n.prototype.IXa=function(e){var a=e.indexOf("://"),f="ws://";0>a?a=0:(5===a&&(f="wss://"),a+=3);var r=e.lastIndexOf("/");0>r&&(r=e.length);return f+e.slice(a,r)};n.prototype.send=function(e){this.su.readyState===WebSocket.CLOSED||this.qX||this.su.send(JSON.stringify(e))};
n.prototype.uN=function(){return Object(ma.b)(this,void 0,void 0,function(){var e,a=this;return Object(ma.d)(this,function(){e=Object(ja.a)("wvsQueryParameters");e.bcid=Object(oa.m)(8);Object(ja.b)("wvsQueryParameters",e);return[2,new Promise(function(f,r){var b=Object(ia.a)(a.url);a.$P=!1;a.su=new WebSocket(b);a.su.onopen=function(){a.qX=!1;a.ji=0;a.nG&&a.nG();f()};a.su.onerror=function(){a.qX=!0};a.su.onclose=function(w){w=w.code;a.DD&&a.DD();1E3!==w&&3E3!==w&&a.VGa(w,f,r)};a.su.onmessage=function(w){w&&
w.data&&(w=JSON.parse(w.data),w.hb?a.send({hb:!0}):w.end?close():a.DU(w))}})]})})};n.prototype.VGa=function(e,a,f){Object(ma.b)(this,void 0,void 0,function(){var r=this;return Object(ma.d)(this,function(){if(this.$P)return a(),[2];this.ji<this.UF?setTimeout(function(){r.$P?a():(r.ji++,Object(na.i)("Failed to connect to server with WebSocket close code ".concat(e,". Reconnecting to WebViewer Server, attempt ").concat(r.ji," of ").concat(r.UF," ...")),r.uN().then(a).catch(f))},this.zha):f(fa.a);return[2]})})};
n.prototype.Rv=function(){var e;void 0===e&&(e=!1);this.ji=0;this.$P=!0;e?this.su.close(3E3):this.su.close();return Promise.resolve()};return n}(),y=function(){function n(e,a,f,r,b,w,ba){void 0===r&&(r=null);void 0===b&&(b=null);void 0===w&&(w=null);void 0===ba&&(ba=null);this.ji=this.hP=this.id=0;this.hF=!1;this.request=null;this.UF=8;this.zha=3E3;e=this.RNa(e);this.url=a?"".concat(e,"/").concat(a,"pf"):"".concat(e,"/pf");this.yQ=f;this.DU=r;this.nG=b;this.DD=w;this.kha=ba}n.prototype.RNa=function(e){var a=
e.lastIndexOf("/");0>a&&(a=e.length);return e.slice(0,a)};n.prototype.cxa=function(e){e=e.split("\n");for(e[e.length-1]&&e.pop();0<e.length&&3>e[e.length-1].length;)"]"===e.pop()&&(this.id=0);0<e.length&&3>e[0].length&&e.shift();for(var a=0;a<e.length;++a)e[a].endsWith(",")&&(e[a]=e[a].substr(0,e[a].length-1));return e};n.prototype.yha=function(){return Object(ma.b)(this,void 0,void 0,function(){var e=this;return Object(ma.d)(this,function(a){switch(a.label){case 0:return this.ji++<this.UF?[4,new Promise(function(f){return setTimeout(function(){e.kha();
e.uN();f()},3E3)})]:[3,2];case 1:a.aa(),a.label=2;case 2:return[2]}})})};n.prototype.XNa=function(e){Object(ma.b)(this,void 0,void 0,function(){var a,f;return Object(ma.d)(this,function(r){switch(r.label){case 0:a=null,f=0,r.label=1;case 1:if(!(f<e.length))return[3,6];a=JSON.parse(e[f]);if(!a)return[3,5];if(!a.end)return[3,2];close();return[3,5];case 2:if(!a.id||Number(a.id)===this.id)return[3,4];Object(na.i)("Reconnecting, new server detected");this.Rv();return[4,this.yha()];case 3:return r.aa(),
[3,5];case 4:a.hb&&Number(a.id)===this.id?this.send({hb:!0}):this.hF||this.DU(a),r.label=5;case 5:return++f,[3,1];case 6:return[2]}})})};n.prototype.OLa=function(e){Object(ma.b)(this,void 0,void 0,function(){var a,f,r;return Object(ma.d)(this,function(b){switch(b.label){case 0:if(!(3<=e.readyState))return[3,2];try{a=e.responseText.length}catch(w){return Object(na.g)("caught exception"),[2]}if(0<a)try{f=this.cxa(e.responseText),0===this.id&&0<f.length&&(r=JSON.parse(f.shift()),this.id=r.id,this.ji=
0),this.XNa(f)}catch(w){}return this.hF?[3,2]:[4,this.l$()];case 1:b.aa(),b.label=2;case 2:return[2]}})})};n.prototype.l$=function(){return Object(ma.b)(this,void 0,void 0,function(){var e=this;return Object(ma.d)(this,function(){return[2,new Promise(function(a,f){function r(){return Object(ma.b)(e,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:f(),this.Rv(),w.label=1;case 1:return this.hF&&this.ji<this.UF?[4,this.yha()]:[3,3];case 2:return w.aa(),[3,1];case 3:return[2]}})})}
e.request=new XMLHttpRequest;e.request.withCredentials=e.yQ;var b=Object(ia.a)(e.url,0!==e.id?{id:String(e.id),uc:String(e.hP)}:{uc:String(e.hP)});e.hP++;e.request.open("GET",b,!0);e.request.setRequestHeader("Cache-Control","no-cache");e.request.setRequestHeader("X-Requested-With","XMLHttpRequest");e.request.onreadystatechange=function(){e.OLa(e.request)};e.request.addEventListener("error",r);e.request.addEventListener("timeout",r);e.request.addEventListener("load",function(){e.nG&&e.nG();a()});e.request.send()})]})})};
n.prototype.uN=function(){var e=Object(ja.a)("wvsQueryParameters");e.bcid=Object(oa.m)(8);Object(ja.b)("wvsQueryParameters",e);this.hP=this.id=0;this.hF=!1;return this.l$()};n.prototype.send=function(e){var a=this,f=new XMLHttpRequest;f.withCredentials=this.yQ;var r=Object(ia.a)(this.url,{id:String(this.id)}),b=new FormData;b.append("data",JSON.stringify(e));f.addEventListener("error",function(){a.Rv()});f.open("POST",r);f.setRequestHeader("X-Requested-With","XMLHttpRequest");f.send(b)};n.prototype.Rv=
function(){this.id=0;this.hF=!0;this.DD&&this.DD();this.request.abort();return Promise.resolve()};return n}();ya=function(){function n(e,a,f){this.s8=e;this.target=a;this.yQ=f}n.prototype.YBa=function(e,a,f,r,b){void 0===e&&(e=!0);void 0===a&&(a=null);void 0===f&&(f=null);void 0===r&&(r=null);void 0===b&&(b=null);return e?new z(this.s8,this.target,a,f,r,b):new y(this.s8,this.target,this.yQ,a,f,r,b)};return n}();ua.a=ya}}]);}).call(this || window)
